
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getState() : Promise<Result<AppState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async incrementClick() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("increment_click") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetClicks() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_clicks") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async index() : Promise<void> {
    await TAURI_INVOKE("index");
},
async getAllTracks() : Promise<FullTrack[]> {
    return await TAURI_INVOKE("get_all_tracks");
},
async getAllAlbums() : Promise<Album[]> {
    return await TAURI_INVOKE("get_all_albums");
},
async getArtistById(id: number) : Promise<Artist> {
    return await TAURI_INVOKE("get_artist_by_id", { id });
},
async getAlbumTracks(albumId: number) : Promise<Track[]> {
    return await TAURI_INVOKE("get_album_tracks", { albumId });
},
async getPlayer() : Promise<Result<AudioPlayer, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_player") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async play() : Promise<Result<AudioPlayer, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("play") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async load(track: FullTrack) : Promise<Result<AudioPlayer, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load", { track }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeQueueIndex(oldIdx: number, newIdx: number) : Promise<Result<AudioPlayer, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_queue_index", { oldIdx, newIdx }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async next() : Promise<Result<AudioPlayer, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("next") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playNext(track: FullTrack) : Promise<Result<AudioPlayer, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("play_next", { track }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playList(list: FullTrack[], idx: number) : Promise<Result<AudioPlayer, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("play_list", { list, idx }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addToQueue(track: FullTrack) : Promise<Result<AudioPlayer, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_to_queue", { track }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clear() : Promise<Result<AudioPlayer, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pause() : Promise<Result<AudioPlayer, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async seek(time: number) : Promise<void> {
    await TAURI_INVOKE("seek", { time });
},
async playTracks(tracks: Track[], index: number) : Promise<Result<AudioPlayer, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("play_tracks", { tracks, index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addListToQueue(fulltracks: FullTrack[] | null, tracks: Track[] | null) : Promise<Result<AudioPlayer, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_list_to_queue", { fulltracks, tracks }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playListNext(fulltracks: FullTrack[] | null, tracks: Track[] | null) : Promise<Result<AudioPlayer, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("play_list_next", { fulltracks, tracks }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fulltrackFromId(id: number) : Promise<FullTrack | null> {
    return await TAURI_INVOKE("fulltrack_from_id", { id });
},
async getLineLyrics(track: FullTrack) : Promise<LineLyrics[]> {
    return await TAURI_INVOKE("get_line_lyrics", { track });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Album = { id: bigint | null; artist_id: bigint; title: string; year: bigint; genre: string | null; album_art: string | null }
export type AppState = { clicks: number }
export type Artist = { id: bigint | null; name: string; genre: string | null }
export type AudioPlayer = { currently_playing: FullTrack | null; state: PlayerState; queue: FullTrack[]; position: number }
export type FullTrack = { track: Track; artist_name: string; album_title: string; album_art: string | null; playlist_position: bigint | null }
export type LineLyrics = { start_time: number; end_time: number | null; line: string; writers: string }
export type PlayerState = "Paused" | "Playing" | "Empty" | "Stopped"
export type Track = { id: bigint | null; album_id: bigint; artist_id: bigint; file_path: string; title: string; track_number: bigint; disc_number: bigint; bpm: bigint; duration: bigint; initial_key: string | null; isrc: string | null; lyrics: string | null; composer: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
